In [2]:
import gymnasium as gym
import seaborn as sns
import matplotlib.pyplot as plt

import torch

import numpy as np
import pandas as pd

# from custom_agent.CTCE.sac_agent import Agent
from custom_agents.CTCE_algorithms.single_agent_SAC_discrete import SAC

env = gym.make("CartPole-v1")

# sac_agent = SAC(env, batch_size = 256, buffer_max_size=100000, use_AE = True, AE_reduc_scale = 2)
sac_agent = SAC(env, batch_size = 256, buffer_max_size=100000)


In [2]:
sac_agent.train(nr_steps = 50000, warmup_steps = 100, learn_delay = 100, learn_freq = 1, learn_weight = 1)

[Episode 50 total reward: 9.000] ~ 
[-0.1561237  -1.7618388   0.21516146  2.7960207 ]
tensor([0.9290, 0.8968])
tensor([-0.0053, -0.1628,  0.1798,  2.3508])
[Episode 100 total reward: 9.000] ~ 
[-0.1460567  -1.7604917   0.22502302  2.7876537 ]
tensor([0.8967, 0.9997])
tensor([-0.0073, -0.4357,  0.1679,  2.4185])


KeyboardInterrupt: 

In [29]:
from gymnasium.utils.save_video import save_video
import gymnasium as gym

env2 = gym.make("CartPole-v1", render_mode = "rgb_array_list")

# test loop
obs, info = env2.reset()
done = 0
truncated = 0
step = 0
for _ in range(1000):
    action = sac_agent.get_action(obs)

    next_obs, reward, done, truncated, info = env2.step(action)

    obs = next_obs

save_video(env2.render(), "videos", name_prefix = "custom_SAC_cartpole", fps=env.metadata["render_fps"], step_starting_index=0)

Moviepy - Building video /home/hkolstee/masterThesis/masterThesis/videos/custom_SAC_cartpole-episode-0.mp4.
Moviepy - Writing video /home/hkolstee/masterThesis/masterThesis/videos/custom_SAC_cartpole-episode-0.mp4



Moviepy - Done !
Moviepy - video ready /home/hkolstee/masterThesis/masterThesis/videos/custom_SAC_cartpole-episode-0.mp4


In [1]:
import gymnasium as gym
import seaborn as sns
import matplotlib.pyplot as plt

import torch

import numpy as np
import pandas as pd

from custom_agents.CTCE_algorithms.single_agent_SAC_continuous import SAC

env = gym.make("Pendulum-v1")

sac_agent = SAC(env, batch_size=256, buffer_max_size=100000)

sac_agent.train(nr_steps = 20000, warmup_steps = 1000, learn_delay = 100, learn_freq = 1, learn_weight = 1)

/home/hkolstee/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


[Episode 50 total reward: -123.423] ~ 


KeyboardInterrupt: 

In [1]:
import gym
import seaborn as sns
import matplotlib.pyplot as plt

import torch

import numpy as np
import pandas as pd

from custom_agents.CTCE_algorithms.single_agent_SAC_continuous import SAC
from custom_agents.utils.citylearn_wrapper import CityLearnWrapper

from citylearn.wrappers import NormalizedSpaceWrapper, StableBaselines3Wrapper
from custom_reward.custom_reward import CustomReward

from citylearn.citylearn import CityLearnEnv

env = CityLearnEnv(schema = "data/schema.json", reward_function = CustomReward, central_agent=True)
env = CityLearnWrapper(env)


sac_agent = SAC(env, batch_size = 256, buffer_max_size = 100000, use_AE = True, AE_reduc_scale = 2, )

sac_agent.train(nr_steps = 100000, warmup_steps = 0, learn_delay = 100, learn_freq = 1, learn_weight = 1)

/home/hkolstee/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


KeyboardInterrupt: 